blank_issues_enabled: false
contact_links:
  - name: Report Security Vulnerability
    url: https://github.com/reponomics/PolicyChecks/security/advisories/new
    about: Please report security vulnerabilities here.
  - name: Report Privacy Concern
    url: https://github.com/reponomics/PolicyChecks/blob/main/PRIVACY.md
    about: Please refer to this documentation to report serious privacy concerns.
